name = "cloudflare-saas-stack"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "cloudflare-saas-stack-db"
database_id = "8e17dd99-b552-4e61-b5d4-84227ff4b14d"
migrations_dir = "./drizzle"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cloudflare-saas-storage"
preview_bucket_name = "cloudflare-saas-storage-dev"
