import {
  Loader2,
  X,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Plus,
  Settings,
  User,
  FileText,
  Trash,
  Upload,
  Download,
  Image,
  File,
} from "lucide-react";

export const Icons = {
  spinner: Loader2,
  close: X,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  add: Plus,
  settings: Settings,
  user: User,
  document: FileText,
  trash: Trash,
  upload: Upload,
  download: Download,
  image: Image,
  file: File,
};
